"""
Project Euler No. 2
====================

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
"""
def fib(this, next):
    while next < 4000000:
        intermediate = this + next
        this = next
        next = intermediate
        return [this] + fib(this, next)
    return [this + next]

print sum([n for n in fib(1,2) if n % 2 == 0])